//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslatorTool.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslatorTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать или открыть новый файл.
        /// </summary>
        internal static string btn {
            get {
                return ResourceManager.GetString("btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться на домашнюю страницу.
        /// </summary>
        internal static string btn1 {
            get {
                return ResourceManager.GetString("btn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить комментарий к выделенной строчке.
        /// </summary>
        internal static string commentForm {
            get {
                return ResourceManager.GetString("commentForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скопировать выделенные строчки.
        /// </summary>
        internal static string CopyText {
            get {
                return ResourceManager.GetString("CopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить выделенную строку.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать выбранный файл..
        /// </summary>
        internal static string EditFile {
            get {
                return ResourceManager.GetString("EditFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст оригинала. Для перемещения используйте стрелки &quot;Вверх-Вниз&quot;. Нажатие выделенной строчки 
        ///или нажатие Enter открывает ее для редактирования..
        /// </summary>
        internal static string EnBox {
            get {
                return ResourceManager.GetString("EnBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспортировать перевод в текстовый файл.
        /// </summary>
        internal static string ExportBtn {
            get {
                return ResourceManager.GetString("ExportBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться на домашнюю страницу.
        /// </summary>
        internal static string GoHome {
            get {
                return ResourceManager.GetString("GoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться на домашнюю страницу.
        /// </summary>
        internal static string GoHome1 {
            get {
                return ResourceManager.GetString("GoHome1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вернуться на домашнюю страницу.
        /// </summary>
        internal static string GoHome2 {
            get {
                return ResourceManager.GetString("GoHome2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть панель поиска текста в интернете.
        /// </summary>
        internal static string GoToSearch {
            get {
                return ResourceManager.GetString("GoToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выделите слово,нажмите горячую клавишу, 
        ///и здесь отобразится перевод.
        /// </summary>
        internal static string multitran {
            get {
                return ResourceManager.GetString("multitran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть текстовый файл.
        /// </summary>
        internal static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вставить выделенные строчки.
        /// </summary>
        internal static string PasteText {
            get {
                return ResourceManager.GetString("PasteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перевод текста. Для перемещения используйте стрелки &quot;Вверх-Вниз&quot;. Нажатие выделенной строчки 
        ///или нажатие Enter открывает ее для редактирования..
        /// </summary>
        internal static string RuBox {
            get {
                return ResourceManager.GetString("RuBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить файл в Базе Данных.
        /// </summary>
        internal static string SaveBD {
            get {
                return ResourceManager.GetString("SaveBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найти текст песни (нажмите Enter или кнопку поиска).
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите часть названия и нажмите Enter, либо задайте остальные фильтры
        ///и нажмите &quot;Применить&quot;.
        /// </summary>
        internal static string searchDB {
            get {
                return ResourceManager.GetString("searchDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найти перевод слова (нажмите Enter).
        /// </summary>
        internal static string searchMultitran {
            get {
                return ResourceManager.GetString("searchMultitran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажмите на необходимый текст, и он откроется для редактирования..
        /// </summary>
        internal static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выделение. Выберите строчку, с которой хотите начать выделение, и нажмите эту 
        ///кнопку. Используйте вертикальный слайдер для выбора области выделения..
        /// </summary>
        internal static string Selection {
            get {
                return ResourceManager.GetString("Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть настройки.
        /// </summary>
        internal static string SettingsGo {
            get {
                return ResourceManager.GetString("SettingsGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки приложения.
        /// </summary>
        internal static string SettingsPanel {
            get {
                return ResourceManager.GetString("SettingsPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разбить текст на строки удобной для редактирования длины.
        /// </summary>
        internal static string SplitTheText {
            get {
                return ResourceManager.GetString("SplitTheText", resourceCulture);
            }
        }
    }
}
